version: '3'
services:
  foundryvtt:
    image: direckthit/fvtt-docker:latest
    container_name: earth14-5e-fvtt
    ports: 
      - 30000:30000
    volumes:
      - ./shared/data:/data/foundryvtt
      - ./shared/host:/host
      - ./shared/app:/opt/foundryvtt/resources/app
    restart: unless-stopped
